###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    db:
      image: mariadb:10.1
      container_name: schlossnagle-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=rootpass
        - MYSQL_DATABASE=testdb
        - MYSQL_USER=testuser
        - MYSQL_PASSWORD=testpass
      ports:
        # - "9194:3306"
        - "3306:3306"
      # networks:
        # - backend

    # adminer:
      # image: dockette/adminer:full-php5
      # restart: always
      # ports:
        # - 8080:8080

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - db
      environment:
        # PMA_HOST: mysql
        # - PMA_ARBITRARY=1
        PMA_ARBITRARY: 1
        PMA_HOST: db
        PMA_PORT: 3306
      ports:
        - '8181:80'
      environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: rootpass
      # networks:
        # - backend
        # - frontend

    webserver:
      image: nginx:alpine
      container_name: schlossnagle-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9191:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: schlossnagle-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
